// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QXSCMsg.proto

#include "QXSCMsg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace QXSCMsg {
PROTOBUF_CONSTEXPR MsgPayload::MsgPayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.bussinesskey_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.clientinfo_)*/nullptr
  , /*decltype(_impl_.serverinfo_)*/nullptr
  , /*decltype(_impl_.msgbase_)*/nullptr
  , /*decltype(_impl_.timestamp_)*/uint64_t{0u}
  , /*decltype(_impl_.transid_)*/0u
  , /*decltype(_impl_.errcode_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MsgPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgPayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgPayloadDefaultTypeInternal() {}
  union {
    MsgPayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgPayloadDefaultTypeInternal _MsgPayload_default_instance_;
PROTOBUF_CONSTEXPR ClientInfo::ClientInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.clientid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ClientInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientInfoDefaultTypeInternal() {}
  union {
    ClientInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientInfoDefaultTypeInternal _ClientInfo_default_instance_;
PROTOBUF_CONSTEXPR ServerInfo::ServerInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.servername_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.serverid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ServerInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerInfoDefaultTypeInternal() {}
  union {
    ServerInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerInfoDefaultTypeInternal _ServerInfo_default_instance_;
PROTOBUF_CONSTEXPR MsgBase::MsgBase(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.clientregister_)*/nullptr
  , /*decltype(_impl_.clientregisterreply_)*/nullptr
  , /*decltype(_impl_.msgtype_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MsgBaseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgBaseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgBaseDefaultTypeInternal() {}
  union {
    MsgBase _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgBaseDefaultTypeInternal _MsgBase_default_instance_;
PROTOBUF_CONSTEXPR ClientRegister::ClientRegister(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.clientid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ClientRegisterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientRegisterDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientRegisterDefaultTypeInternal() {}
  union {
    ClientRegister _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientRegisterDefaultTypeInternal _ClientRegister_default_instance_;
PROTOBUF_CONSTEXPR ClientRegisterReply::ClientRegisterReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.errcode_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ClientRegisterReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientRegisterReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientRegisterReplyDefaultTypeInternal() {}
  union {
    ClientRegisterReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientRegisterReplyDefaultTypeInternal _ClientRegisterReply_default_instance_;
}  // namespace QXSCMsg
static ::_pb::Metadata file_level_metadata_QXSCMsg_2eproto[6];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_QXSCMsg_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_QXSCMsg_2eproto = nullptr;

const uint32_t TableStruct_QXSCMsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgPayload, _impl_.transid_),
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgPayload, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgPayload, _impl_.bussinesskey_),
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgPayload, _impl_.clientinfo_),
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgPayload, _impl_.serverinfo_),
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgPayload, _impl_.errcode_),
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgPayload, _impl_.msgbase_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::ClientInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::ClientInfo, _impl_.clientid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::ServerInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::ServerInfo, _impl_.serverid_),
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::ServerInfo, _impl_.servername_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgBase, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgBase, _impl_.msgtype_),
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgBase, _impl_.clientregister_),
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::MsgBase, _impl_.clientregisterreply_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::ClientRegister, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::ClientRegister, _impl_.clientid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::ClientRegisterReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::QXSCMsg::ClientRegisterReply, _impl_.errcode_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::QXSCMsg::MsgPayload)},
  { 13, -1, -1, sizeof(::QXSCMsg::ClientInfo)},
  { 20, -1, -1, sizeof(::QXSCMsg::ServerInfo)},
  { 28, -1, -1, sizeof(::QXSCMsg::MsgBase)},
  { 37, -1, -1, sizeof(::QXSCMsg::ClientRegister)},
  { 44, -1, -1, sizeof(::QXSCMsg::ClientRegisterReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::QXSCMsg::_MsgPayload_default_instance_._instance,
  &::QXSCMsg::_ClientInfo_default_instance_._instance,
  &::QXSCMsg::_ServerInfo_default_instance_._instance,
  &::QXSCMsg::_MsgBase_default_instance_._instance,
  &::QXSCMsg::_ClientRegister_default_instance_._instance,
  &::QXSCMsg::_ClientRegisterReply_default_instance_._instance,
};

const char descriptor_table_protodef_QXSCMsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rQXSCMsg.proto\022\007QXSCMsg\"\314\001\n\nMsgPayload\022"
  "\017\n\007transId\030\001 \001(\r\022\021\n\ttimestamp\030\002 \001(\004\022\024\n\014b"
  "ussinessKey\030\003 \001(\t\022\'\n\nclientInfo\030\004 \001(\0132\023."
  "QXSCMsg.ClientInfo\022\'\n\nserverInfo\030\005 \001(\0132\023"
  ".QXSCMsg.ServerInfo\022\017\n\007errCode\030\006 \001(\005\022!\n\007"
  "msgBase\030\007 \001(\0132\020.QXSCMsg.MsgBase\"\036\n\nClien"
  "tInfo\022\020\n\010clientId\030\001 \001(\r\"2\n\nServerInfo\022\020\n"
  "\010serverId\030\001 \001(\r\022\022\n\nserverName\030\002 \001(\t\"\206\001\n\007"
  "MsgBase\022\017\n\007msgType\030\001 \001(\r\022/\n\016clientRegist"
  "er\030\002 \001(\0132\027.QXSCMsg.ClientRegister\0229\n\023cli"
  "entRegisterReply\030\003 \001(\0132\034.QXSCMsg.ClientR"
  "egisterReply\"\"\n\016ClientRegister\022\020\n\010client"
  "Id\030\001 \001(\r\"&\n\023ClientRegisterReply\022\017\n\007errCo"
  "de\030\001 \001(\005*[\n\007MsgType\022\026\n\022QX_MSG_TYPE_UKNOW"
  "N\020\000\022\030\n\024QX_MSG_TYPE_REGISTER\020\001\022\036\n\032QX_MSG_"
  "TYPE_REGISTER_REPLY\020\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_QXSCMsg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_QXSCMsg_2eproto = {
    false, false, 629, descriptor_table_protodef_QXSCMsg_2eproto,
    "QXSCMsg.proto",
    &descriptor_table_QXSCMsg_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_QXSCMsg_2eproto::offsets,
    file_level_metadata_QXSCMsg_2eproto, file_level_enum_descriptors_QXSCMsg_2eproto,
    file_level_service_descriptors_QXSCMsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_QXSCMsg_2eproto_getter() {
  return &descriptor_table_QXSCMsg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_QXSCMsg_2eproto(&descriptor_table_QXSCMsg_2eproto);
namespace QXSCMsg {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_QXSCMsg_2eproto);
  return file_level_enum_descriptors_QXSCMsg_2eproto[0];
}
bool MsgType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class MsgPayload::_Internal {
 public:
  static const ::QXSCMsg::ClientInfo& clientinfo(const MsgPayload* msg);
  static const ::QXSCMsg::ServerInfo& serverinfo(const MsgPayload* msg);
  static const ::QXSCMsg::MsgBase& msgbase(const MsgPayload* msg);
};

const ::QXSCMsg::ClientInfo&
MsgPayload::_Internal::clientinfo(const MsgPayload* msg) {
  return *msg->_impl_.clientinfo_;
}
const ::QXSCMsg::ServerInfo&
MsgPayload::_Internal::serverinfo(const MsgPayload* msg) {
  return *msg->_impl_.serverinfo_;
}
const ::QXSCMsg::MsgBase&
MsgPayload::_Internal::msgbase(const MsgPayload* msg) {
  return *msg->_impl_.msgbase_;
}
MsgPayload::MsgPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:QXSCMsg.MsgPayload)
}
MsgPayload::MsgPayload(const MsgPayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MsgPayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.bussinesskey_){}
    , decltype(_impl_.clientinfo_){nullptr}
    , decltype(_impl_.serverinfo_){nullptr}
    , decltype(_impl_.msgbase_){nullptr}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.transid_){}
    , decltype(_impl_.errcode_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.bussinesskey_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bussinesskey_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_bussinesskey().empty()) {
    _this->_impl_.bussinesskey_.Set(from._internal_bussinesskey(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_clientinfo()) {
    _this->_impl_.clientinfo_ = new ::QXSCMsg::ClientInfo(*from._impl_.clientinfo_);
  }
  if (from._internal_has_serverinfo()) {
    _this->_impl_.serverinfo_ = new ::QXSCMsg::ServerInfo(*from._impl_.serverinfo_);
  }
  if (from._internal_has_msgbase()) {
    _this->_impl_.msgbase_ = new ::QXSCMsg::MsgBase(*from._impl_.msgbase_);
  }
  ::memcpy(&_impl_.timestamp_, &from._impl_.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.errcode_) -
    reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.errcode_));
  // @@protoc_insertion_point(copy_constructor:QXSCMsg.MsgPayload)
}

inline void MsgPayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.bussinesskey_){}
    , decltype(_impl_.clientinfo_){nullptr}
    , decltype(_impl_.serverinfo_){nullptr}
    , decltype(_impl_.msgbase_){nullptr}
    , decltype(_impl_.timestamp_){uint64_t{0u}}
    , decltype(_impl_.transid_){0u}
    , decltype(_impl_.errcode_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.bussinesskey_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bussinesskey_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MsgPayload::~MsgPayload() {
  // @@protoc_insertion_point(destructor:QXSCMsg.MsgPayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MsgPayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.bussinesskey_.Destroy();
  if (this != internal_default_instance()) delete _impl_.clientinfo_;
  if (this != internal_default_instance()) delete _impl_.serverinfo_;
  if (this != internal_default_instance()) delete _impl_.msgbase_;
}

void MsgPayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MsgPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:QXSCMsg.MsgPayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bussinesskey_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.clientinfo_ != nullptr) {
    delete _impl_.clientinfo_;
  }
  _impl_.clientinfo_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.serverinfo_ != nullptr) {
    delete _impl_.serverinfo_;
  }
  _impl_.serverinfo_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.msgbase_ != nullptr) {
    delete _impl_.msgbase_;
  }
  _impl_.msgbase_ = nullptr;
  ::memset(&_impl_.timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.errcode_) -
      reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.errcode_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MsgPayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 transId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.transid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 timestamp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string bussinessKey = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_bussinesskey();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "QXSCMsg.MsgPayload.bussinessKey"));
        } else
          goto handle_unusual;
        continue;
      // .QXSCMsg.ClientInfo clientInfo = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_clientinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .QXSCMsg.ServerInfo serverInfo = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_serverinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 errCode = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.errcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .QXSCMsg.MsgBase msgBase = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_msgbase(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MsgPayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QXSCMsg.MsgPayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 transId = 1;
  if (this->_internal_transid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_transid(), target);
  }

  // uint64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_timestamp(), target);
  }

  // string bussinessKey = 3;
  if (!this->_internal_bussinesskey().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_bussinesskey().data(), static_cast<int>(this->_internal_bussinesskey().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "QXSCMsg.MsgPayload.bussinessKey");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_bussinesskey(), target);
  }

  // .QXSCMsg.ClientInfo clientInfo = 4;
  if (this->_internal_has_clientinfo()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::clientinfo(this),
        _Internal::clientinfo(this).GetCachedSize(), target, stream);
  }

  // .QXSCMsg.ServerInfo serverInfo = 5;
  if (this->_internal_has_serverinfo()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::serverinfo(this),
        _Internal::serverinfo(this).GetCachedSize(), target, stream);
  }

  // int32 errCode = 6;
  if (this->_internal_errcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_errcode(), target);
  }

  // .QXSCMsg.MsgBase msgBase = 7;
  if (this->_internal_has_msgbase()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::msgbase(this),
        _Internal::msgbase(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QXSCMsg.MsgPayload)
  return target;
}

size_t MsgPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QXSCMsg.MsgPayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string bussinessKey = 3;
  if (!this->_internal_bussinesskey().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_bussinesskey());
  }

  // .QXSCMsg.ClientInfo clientInfo = 4;
  if (this->_internal_has_clientinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.clientinfo_);
  }

  // .QXSCMsg.ServerInfo serverInfo = 5;
  if (this->_internal_has_serverinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.serverinfo_);
  }

  // .QXSCMsg.MsgBase msgBase = 7;
  if (this->_internal_has_msgbase()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.msgbase_);
  }

  // uint64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timestamp());
  }

  // uint32 transId = 1;
  if (this->_internal_transid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_transid());
  }

  // int32 errCode = 6;
  if (this->_internal_errcode() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_errcode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgPayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MsgPayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgPayload::GetClassData() const { return &_class_data_; }


void MsgPayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MsgPayload*>(&to_msg);
  auto& from = static_cast<const MsgPayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:QXSCMsg.MsgPayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_bussinesskey().empty()) {
    _this->_internal_set_bussinesskey(from._internal_bussinesskey());
  }
  if (from._internal_has_clientinfo()) {
    _this->_internal_mutable_clientinfo()->::QXSCMsg::ClientInfo::MergeFrom(
        from._internal_clientinfo());
  }
  if (from._internal_has_serverinfo()) {
    _this->_internal_mutable_serverinfo()->::QXSCMsg::ServerInfo::MergeFrom(
        from._internal_serverinfo());
  }
  if (from._internal_has_msgbase()) {
    _this->_internal_mutable_msgbase()->::QXSCMsg::MsgBase::MergeFrom(
        from._internal_msgbase());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (from._internal_transid() != 0) {
    _this->_internal_set_transid(from._internal_transid());
  }
  if (from._internal_errcode() != 0) {
    _this->_internal_set_errcode(from._internal_errcode());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MsgPayload::CopyFrom(const MsgPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QXSCMsg.MsgPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgPayload::IsInitialized() const {
  return true;
}

void MsgPayload::InternalSwap(MsgPayload* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.bussinesskey_, lhs_arena,
      &other->_impl_.bussinesskey_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MsgPayload, _impl_.errcode_)
      + sizeof(MsgPayload::_impl_.errcode_)
      - PROTOBUF_FIELD_OFFSET(MsgPayload, _impl_.clientinfo_)>(
          reinterpret_cast<char*>(&_impl_.clientinfo_),
          reinterpret_cast<char*>(&other->_impl_.clientinfo_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MsgPayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_QXSCMsg_2eproto_getter, &descriptor_table_QXSCMsg_2eproto_once,
      file_level_metadata_QXSCMsg_2eproto[0]);
}

// ===================================================================

class ClientInfo::_Internal {
 public:
};

ClientInfo::ClientInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:QXSCMsg.ClientInfo)
}
ClientInfo::ClientInfo(const ClientInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ClientInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.clientid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.clientid_ = from._impl_.clientid_;
  // @@protoc_insertion_point(copy_constructor:QXSCMsg.ClientInfo)
}

inline void ClientInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.clientid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ClientInfo::~ClientInfo() {
  // @@protoc_insertion_point(destructor:QXSCMsg.ClientInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ClientInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ClientInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ClientInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:QXSCMsg.ClientInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.clientid_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClientInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 clientId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.clientid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ClientInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QXSCMsg.ClientInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 clientId = 1;
  if (this->_internal_clientid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_clientid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QXSCMsg.ClientInfo)
  return target;
}

size_t ClientInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QXSCMsg.ClientInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 clientId = 1;
  if (this->_internal_clientid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_clientid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ClientInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ClientInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ClientInfo::GetClassData() const { return &_class_data_; }


void ClientInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ClientInfo*>(&to_msg);
  auto& from = static_cast<const ClientInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:QXSCMsg.ClientInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_clientid() != 0) {
    _this->_internal_set_clientid(from._internal_clientid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ClientInfo::CopyFrom(const ClientInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QXSCMsg.ClientInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientInfo::IsInitialized() const {
  return true;
}

void ClientInfo::InternalSwap(ClientInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.clientid_, other->_impl_.clientid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ClientInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_QXSCMsg_2eproto_getter, &descriptor_table_QXSCMsg_2eproto_once,
      file_level_metadata_QXSCMsg_2eproto[1]);
}

// ===================================================================

class ServerInfo::_Internal {
 public:
};

ServerInfo::ServerInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:QXSCMsg.ServerInfo)
}
ServerInfo::ServerInfo(const ServerInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ServerInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.servername_){}
    , decltype(_impl_.serverid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.servername_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.servername_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_servername().empty()) {
    _this->_impl_.servername_.Set(from._internal_servername(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.serverid_ = from._impl_.serverid_;
  // @@protoc_insertion_point(copy_constructor:QXSCMsg.ServerInfo)
}

inline void ServerInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.servername_){}
    , decltype(_impl_.serverid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.servername_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.servername_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ServerInfo::~ServerInfo() {
  // @@protoc_insertion_point(destructor:QXSCMsg.ServerInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ServerInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.servername_.Destroy();
}

void ServerInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ServerInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:QXSCMsg.ServerInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.servername_.ClearToEmpty();
  _impl_.serverid_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ServerInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 serverId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.serverid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string serverName = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_servername();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "QXSCMsg.ServerInfo.serverName"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ServerInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QXSCMsg.ServerInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 serverId = 1;
  if (this->_internal_serverid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_serverid(), target);
  }

  // string serverName = 2;
  if (!this->_internal_servername().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_servername().data(), static_cast<int>(this->_internal_servername().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "QXSCMsg.ServerInfo.serverName");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_servername(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QXSCMsg.ServerInfo)
  return target;
}

size_t ServerInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QXSCMsg.ServerInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string serverName = 2;
  if (!this->_internal_servername().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_servername());
  }

  // uint32 serverId = 1;
  if (this->_internal_serverid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_serverid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ServerInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ServerInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ServerInfo::GetClassData() const { return &_class_data_; }


void ServerInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ServerInfo*>(&to_msg);
  auto& from = static_cast<const ServerInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:QXSCMsg.ServerInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_servername().empty()) {
    _this->_internal_set_servername(from._internal_servername());
  }
  if (from._internal_serverid() != 0) {
    _this->_internal_set_serverid(from._internal_serverid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ServerInfo::CopyFrom(const ServerInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QXSCMsg.ServerInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerInfo::IsInitialized() const {
  return true;
}

void ServerInfo::InternalSwap(ServerInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.servername_, lhs_arena,
      &other->_impl_.servername_, rhs_arena
  );
  swap(_impl_.serverid_, other->_impl_.serverid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ServerInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_QXSCMsg_2eproto_getter, &descriptor_table_QXSCMsg_2eproto_once,
      file_level_metadata_QXSCMsg_2eproto[2]);
}

// ===================================================================

class MsgBase::_Internal {
 public:
  static const ::QXSCMsg::ClientRegister& clientregister(const MsgBase* msg);
  static const ::QXSCMsg::ClientRegisterReply& clientregisterreply(const MsgBase* msg);
};

const ::QXSCMsg::ClientRegister&
MsgBase::_Internal::clientregister(const MsgBase* msg) {
  return *msg->_impl_.clientregister_;
}
const ::QXSCMsg::ClientRegisterReply&
MsgBase::_Internal::clientregisterreply(const MsgBase* msg) {
  return *msg->_impl_.clientregisterreply_;
}
MsgBase::MsgBase(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:QXSCMsg.MsgBase)
}
MsgBase::MsgBase(const MsgBase& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MsgBase* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.clientregister_){nullptr}
    , decltype(_impl_.clientregisterreply_){nullptr}
    , decltype(_impl_.msgtype_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_clientregister()) {
    _this->_impl_.clientregister_ = new ::QXSCMsg::ClientRegister(*from._impl_.clientregister_);
  }
  if (from._internal_has_clientregisterreply()) {
    _this->_impl_.clientregisterreply_ = new ::QXSCMsg::ClientRegisterReply(*from._impl_.clientregisterreply_);
  }
  _this->_impl_.msgtype_ = from._impl_.msgtype_;
  // @@protoc_insertion_point(copy_constructor:QXSCMsg.MsgBase)
}

inline void MsgBase::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.clientregister_){nullptr}
    , decltype(_impl_.clientregisterreply_){nullptr}
    , decltype(_impl_.msgtype_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MsgBase::~MsgBase() {
  // @@protoc_insertion_point(destructor:QXSCMsg.MsgBase)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MsgBase::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.clientregister_;
  if (this != internal_default_instance()) delete _impl_.clientregisterreply_;
}

void MsgBase::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MsgBase::Clear() {
// @@protoc_insertion_point(message_clear_start:QXSCMsg.MsgBase)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.clientregister_ != nullptr) {
    delete _impl_.clientregister_;
  }
  _impl_.clientregister_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.clientregisterreply_ != nullptr) {
    delete _impl_.clientregisterreply_;
  }
  _impl_.clientregisterreply_ = nullptr;
  _impl_.msgtype_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MsgBase::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 msgType = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.msgtype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .QXSCMsg.ClientRegister clientRegister = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_clientregister(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .QXSCMsg.ClientRegisterReply clientRegisterReply = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_clientregisterreply(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MsgBase::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QXSCMsg.MsgBase)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 msgType = 1;
  if (this->_internal_msgtype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_msgtype(), target);
  }

  // .QXSCMsg.ClientRegister clientRegister = 2;
  if (this->_internal_has_clientregister()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::clientregister(this),
        _Internal::clientregister(this).GetCachedSize(), target, stream);
  }

  // .QXSCMsg.ClientRegisterReply clientRegisterReply = 3;
  if (this->_internal_has_clientregisterreply()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::clientregisterreply(this),
        _Internal::clientregisterreply(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QXSCMsg.MsgBase)
  return target;
}

size_t MsgBase::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QXSCMsg.MsgBase)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .QXSCMsg.ClientRegister clientRegister = 2;
  if (this->_internal_has_clientregister()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.clientregister_);
  }

  // .QXSCMsg.ClientRegisterReply clientRegisterReply = 3;
  if (this->_internal_has_clientregisterreply()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.clientregisterreply_);
  }

  // uint32 msgType = 1;
  if (this->_internal_msgtype() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_msgtype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgBase::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MsgBase::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgBase::GetClassData() const { return &_class_data_; }


void MsgBase::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MsgBase*>(&to_msg);
  auto& from = static_cast<const MsgBase&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:QXSCMsg.MsgBase)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_clientregister()) {
    _this->_internal_mutable_clientregister()->::QXSCMsg::ClientRegister::MergeFrom(
        from._internal_clientregister());
  }
  if (from._internal_has_clientregisterreply()) {
    _this->_internal_mutable_clientregisterreply()->::QXSCMsg::ClientRegisterReply::MergeFrom(
        from._internal_clientregisterreply());
  }
  if (from._internal_msgtype() != 0) {
    _this->_internal_set_msgtype(from._internal_msgtype());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MsgBase::CopyFrom(const MsgBase& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QXSCMsg.MsgBase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgBase::IsInitialized() const {
  return true;
}

void MsgBase::InternalSwap(MsgBase* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MsgBase, _impl_.msgtype_)
      + sizeof(MsgBase::_impl_.msgtype_)
      - PROTOBUF_FIELD_OFFSET(MsgBase, _impl_.clientregister_)>(
          reinterpret_cast<char*>(&_impl_.clientregister_),
          reinterpret_cast<char*>(&other->_impl_.clientregister_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MsgBase::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_QXSCMsg_2eproto_getter, &descriptor_table_QXSCMsg_2eproto_once,
      file_level_metadata_QXSCMsg_2eproto[3]);
}

// ===================================================================

class ClientRegister::_Internal {
 public:
};

ClientRegister::ClientRegister(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:QXSCMsg.ClientRegister)
}
ClientRegister::ClientRegister(const ClientRegister& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ClientRegister* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.clientid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.clientid_ = from._impl_.clientid_;
  // @@protoc_insertion_point(copy_constructor:QXSCMsg.ClientRegister)
}

inline void ClientRegister::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.clientid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ClientRegister::~ClientRegister() {
  // @@protoc_insertion_point(destructor:QXSCMsg.ClientRegister)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ClientRegister::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ClientRegister::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ClientRegister::Clear() {
// @@protoc_insertion_point(message_clear_start:QXSCMsg.ClientRegister)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.clientid_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClientRegister::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 clientId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.clientid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ClientRegister::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QXSCMsg.ClientRegister)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 clientId = 1;
  if (this->_internal_clientid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_clientid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QXSCMsg.ClientRegister)
  return target;
}

size_t ClientRegister::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QXSCMsg.ClientRegister)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 clientId = 1;
  if (this->_internal_clientid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_clientid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ClientRegister::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ClientRegister::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ClientRegister::GetClassData() const { return &_class_data_; }


void ClientRegister::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ClientRegister*>(&to_msg);
  auto& from = static_cast<const ClientRegister&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:QXSCMsg.ClientRegister)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_clientid() != 0) {
    _this->_internal_set_clientid(from._internal_clientid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ClientRegister::CopyFrom(const ClientRegister& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QXSCMsg.ClientRegister)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientRegister::IsInitialized() const {
  return true;
}

void ClientRegister::InternalSwap(ClientRegister* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.clientid_, other->_impl_.clientid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ClientRegister::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_QXSCMsg_2eproto_getter, &descriptor_table_QXSCMsg_2eproto_once,
      file_level_metadata_QXSCMsg_2eproto[4]);
}

// ===================================================================

class ClientRegisterReply::_Internal {
 public:
};

ClientRegisterReply::ClientRegisterReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:QXSCMsg.ClientRegisterReply)
}
ClientRegisterReply::ClientRegisterReply(const ClientRegisterReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ClientRegisterReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.errcode_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.errcode_ = from._impl_.errcode_;
  // @@protoc_insertion_point(copy_constructor:QXSCMsg.ClientRegisterReply)
}

inline void ClientRegisterReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.errcode_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ClientRegisterReply::~ClientRegisterReply() {
  // @@protoc_insertion_point(destructor:QXSCMsg.ClientRegisterReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ClientRegisterReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ClientRegisterReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ClientRegisterReply::Clear() {
// @@protoc_insertion_point(message_clear_start:QXSCMsg.ClientRegisterReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.errcode_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClientRegisterReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 errCode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.errcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ClientRegisterReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QXSCMsg.ClientRegisterReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 errCode = 1;
  if (this->_internal_errcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_errcode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QXSCMsg.ClientRegisterReply)
  return target;
}

size_t ClientRegisterReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QXSCMsg.ClientRegisterReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 errCode = 1;
  if (this->_internal_errcode() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_errcode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ClientRegisterReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ClientRegisterReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ClientRegisterReply::GetClassData() const { return &_class_data_; }


void ClientRegisterReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ClientRegisterReply*>(&to_msg);
  auto& from = static_cast<const ClientRegisterReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:QXSCMsg.ClientRegisterReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_errcode() != 0) {
    _this->_internal_set_errcode(from._internal_errcode());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ClientRegisterReply::CopyFrom(const ClientRegisterReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QXSCMsg.ClientRegisterReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientRegisterReply::IsInitialized() const {
  return true;
}

void ClientRegisterReply::InternalSwap(ClientRegisterReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.errcode_, other->_impl_.errcode_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ClientRegisterReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_QXSCMsg_2eproto_getter, &descriptor_table_QXSCMsg_2eproto_once,
      file_level_metadata_QXSCMsg_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace QXSCMsg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::QXSCMsg::MsgPayload*
Arena::CreateMaybeMessage< ::QXSCMsg::MsgPayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::QXSCMsg::MsgPayload >(arena);
}
template<> PROTOBUF_NOINLINE ::QXSCMsg::ClientInfo*
Arena::CreateMaybeMessage< ::QXSCMsg::ClientInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::QXSCMsg::ClientInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::QXSCMsg::ServerInfo*
Arena::CreateMaybeMessage< ::QXSCMsg::ServerInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::QXSCMsg::ServerInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::QXSCMsg::MsgBase*
Arena::CreateMaybeMessage< ::QXSCMsg::MsgBase >(Arena* arena) {
  return Arena::CreateMessageInternal< ::QXSCMsg::MsgBase >(arena);
}
template<> PROTOBUF_NOINLINE ::QXSCMsg::ClientRegister*
Arena::CreateMaybeMessage< ::QXSCMsg::ClientRegister >(Arena* arena) {
  return Arena::CreateMessageInternal< ::QXSCMsg::ClientRegister >(arena);
}
template<> PROTOBUF_NOINLINE ::QXSCMsg::ClientRegisterReply*
Arena::CreateMaybeMessage< ::QXSCMsg::ClientRegisterReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::QXSCMsg::ClientRegisterReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
