// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QXMSMsg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_QXMSMsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_QXMSMsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_QXMSMsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_QXMSMsg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_QXMSMsg_2eproto;
namespace QXMSMsg {
class ClientInfo;
struct ClientInfoDefaultTypeInternal;
extern ClientInfoDefaultTypeInternal _ClientInfo_default_instance_;
class MsgBase;
struct MsgBaseDefaultTypeInternal;
extern MsgBaseDefaultTypeInternal _MsgBase_default_instance_;
class MsgPayload;
struct MsgPayloadDefaultTypeInternal;
extern MsgPayloadDefaultTypeInternal _MsgPayload_default_instance_;
class ServerInfo;
struct ServerInfoDefaultTypeInternal;
extern ServerInfoDefaultTypeInternal _ServerInfo_default_instance_;
class SvrHealthReport;
struct SvrHealthReportDefaultTypeInternal;
extern SvrHealthReportDefaultTypeInternal _SvrHealthReport_default_instance_;
}  // namespace QXMSMsg
PROTOBUF_NAMESPACE_OPEN
template<> ::QXMSMsg::ClientInfo* Arena::CreateMaybeMessage<::QXMSMsg::ClientInfo>(Arena*);
template<> ::QXMSMsg::MsgBase* Arena::CreateMaybeMessage<::QXMSMsg::MsgBase>(Arena*);
template<> ::QXMSMsg::MsgPayload* Arena::CreateMaybeMessage<::QXMSMsg::MsgPayload>(Arena*);
template<> ::QXMSMsg::ServerInfo* Arena::CreateMaybeMessage<::QXMSMsg::ServerInfo>(Arena*);
template<> ::QXMSMsg::SvrHealthReport* Arena::CreateMaybeMessage<::QXMSMsg::SvrHealthReport>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace QXMSMsg {

enum MsgType : int {
  QX_MS_MSG_TYPE_UKNOWN = 0,
  QX_MS_MSG_TYPE_SVR_HEALTH_REPORT = 1,
  QX_MS_MSG_TYPE_STOP_WORKER = 3,
  QX_MS_MSG_TYPE_STOP_WORKER_REPLY = 4,
  QX_MS_MSG_TYPE_START_WORKER = 5,
  QX_MS_MSG_TYPE_START_WORKER_REPLY = 6,
  MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MsgType_IsValid(int value);
constexpr MsgType MsgType_MIN = QX_MS_MSG_TYPE_UKNOWN;
constexpr MsgType MsgType_MAX = QX_MS_MSG_TYPE_START_WORKER_REPLY;
constexpr int MsgType_ARRAYSIZE = MsgType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgType_descriptor();
template<typename T>
inline const std::string& MsgType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MsgType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MsgType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MsgType_descriptor(), enum_t_value);
}
inline bool MsgType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MsgType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MsgType>(
    MsgType_descriptor(), name, value);
}
// ===================================================================

class MsgPayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QXMSMsg.MsgPayload) */ {
 public:
  inline MsgPayload() : MsgPayload(nullptr) {}
  ~MsgPayload() override;
  explicit PROTOBUF_CONSTEXPR MsgPayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MsgPayload(const MsgPayload& from);
  MsgPayload(MsgPayload&& from) noexcept
    : MsgPayload() {
    *this = ::std::move(from);
  }

  inline MsgPayload& operator=(const MsgPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgPayload& operator=(MsgPayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MsgPayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const MsgPayload* internal_default_instance() {
    return reinterpret_cast<const MsgPayload*>(
               &_MsgPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MsgPayload& a, MsgPayload& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgPayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgPayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MsgPayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MsgPayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MsgPayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MsgPayload& from) {
    MsgPayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgPayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QXMSMsg.MsgPayload";
  }
  protected:
  explicit MsgPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBussinessKeyFieldNumber = 3,
    kServerInfoFieldNumber = 5,
    kMsgBaseFieldNumber = 7,
    kTimestampFieldNumber = 2,
    kTransIdFieldNumber = 1,
    kErrCodeFieldNumber = 6,
  };
  // string bussinessKey = 3;
  void clear_bussinesskey();
  const std::string& bussinesskey() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bussinesskey(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bussinesskey();
  PROTOBUF_NODISCARD std::string* release_bussinesskey();
  void set_allocated_bussinesskey(std::string* bussinesskey);
  private:
  const std::string& _internal_bussinesskey() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bussinesskey(const std::string& value);
  std::string* _internal_mutable_bussinesskey();
  public:

  // .QXMSMsg.ServerInfo serverInfo = 5;
  bool has_serverinfo() const;
  private:
  bool _internal_has_serverinfo() const;
  public:
  void clear_serverinfo();
  const ::QXMSMsg::ServerInfo& serverinfo() const;
  PROTOBUF_NODISCARD ::QXMSMsg::ServerInfo* release_serverinfo();
  ::QXMSMsg::ServerInfo* mutable_serverinfo();
  void set_allocated_serverinfo(::QXMSMsg::ServerInfo* serverinfo);
  private:
  const ::QXMSMsg::ServerInfo& _internal_serverinfo() const;
  ::QXMSMsg::ServerInfo* _internal_mutable_serverinfo();
  public:
  void unsafe_arena_set_allocated_serverinfo(
      ::QXMSMsg::ServerInfo* serverinfo);
  ::QXMSMsg::ServerInfo* unsafe_arena_release_serverinfo();

  // .QXMSMsg.MsgBase msgBase = 7;
  bool has_msgbase() const;
  private:
  bool _internal_has_msgbase() const;
  public:
  void clear_msgbase();
  const ::QXMSMsg::MsgBase& msgbase() const;
  PROTOBUF_NODISCARD ::QXMSMsg::MsgBase* release_msgbase();
  ::QXMSMsg::MsgBase* mutable_msgbase();
  void set_allocated_msgbase(::QXMSMsg::MsgBase* msgbase);
  private:
  const ::QXMSMsg::MsgBase& _internal_msgbase() const;
  ::QXMSMsg::MsgBase* _internal_mutable_msgbase();
  public:
  void unsafe_arena_set_allocated_msgbase(
      ::QXMSMsg::MsgBase* msgbase);
  ::QXMSMsg::MsgBase* unsafe_arena_release_msgbase();

  // uint64 timestamp = 2;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // uint32 transId = 1;
  void clear_transid();
  uint32_t transid() const;
  void set_transid(uint32_t value);
  private:
  uint32_t _internal_transid() const;
  void _internal_set_transid(uint32_t value);
  public:

  // int32 errCode = 6;
  void clear_errcode();
  int32_t errcode() const;
  void set_errcode(int32_t value);
  private:
  int32_t _internal_errcode() const;
  void _internal_set_errcode(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:QXMSMsg.MsgPayload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bussinesskey_;
    ::QXMSMsg::ServerInfo* serverinfo_;
    ::QXMSMsg::MsgBase* msgbase_;
    uint64_t timestamp_;
    uint32_t transid_;
    int32_t errcode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_QXMSMsg_2eproto;
};
// -------------------------------------------------------------------

class ServerInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QXMSMsg.ServerInfo) */ {
 public:
  inline ServerInfo() : ServerInfo(nullptr) {}
  ~ServerInfo() override;
  explicit PROTOBUF_CONSTEXPR ServerInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerInfo(const ServerInfo& from);
  ServerInfo(ServerInfo&& from) noexcept
    : ServerInfo() {
    *this = ::std::move(from);
  }

  inline ServerInfo& operator=(const ServerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerInfo& operator=(ServerInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerInfo* internal_default_instance() {
    return reinterpret_cast<const ServerInfo*>(
               &_ServerInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ServerInfo& a, ServerInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ServerInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ServerInfo& from) {
    ServerInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QXMSMsg.ServerInfo";
  }
  protected:
  explicit ServerInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerNameFieldNumber = 2,
    kServerIdFieldNumber = 1,
  };
  // string serverName = 2;
  void clear_servername();
  const std::string& servername() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_servername(ArgT0&& arg0, ArgT... args);
  std::string* mutable_servername();
  PROTOBUF_NODISCARD std::string* release_servername();
  void set_allocated_servername(std::string* servername);
  private:
  const std::string& _internal_servername() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_servername(const std::string& value);
  std::string* _internal_mutable_servername();
  public:

  // uint32 serverId = 1;
  void clear_serverid();
  uint32_t serverid() const;
  void set_serverid(uint32_t value);
  private:
  uint32_t _internal_serverid() const;
  void _internal_set_serverid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:QXMSMsg.ServerInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr servername_;
    uint32_t serverid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_QXMSMsg_2eproto;
};
// -------------------------------------------------------------------

class MsgBase final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QXMSMsg.MsgBase) */ {
 public:
  inline MsgBase() : MsgBase(nullptr) {}
  ~MsgBase() override;
  explicit PROTOBUF_CONSTEXPR MsgBase(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MsgBase(const MsgBase& from);
  MsgBase(MsgBase&& from) noexcept
    : MsgBase() {
    *this = ::std::move(from);
  }

  inline MsgBase& operator=(const MsgBase& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgBase& operator=(MsgBase&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MsgBase& default_instance() {
    return *internal_default_instance();
  }
  static inline const MsgBase* internal_default_instance() {
    return reinterpret_cast<const MsgBase*>(
               &_MsgBase_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MsgBase& a, MsgBase& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgBase* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgBase* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MsgBase* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MsgBase>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MsgBase& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MsgBase& from) {
    MsgBase::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgBase* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QXMSMsg.MsgBase";
  }
  protected:
  explicit MsgBase(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSvrHealthReportFieldNumber = 2,
    kMsgTypeFieldNumber = 1,
  };
  // .QXMSMsg.SvrHealthReport svrHealthReport = 2;
  bool has_svrhealthreport() const;
  private:
  bool _internal_has_svrhealthreport() const;
  public:
  void clear_svrhealthreport();
  const ::QXMSMsg::SvrHealthReport& svrhealthreport() const;
  PROTOBUF_NODISCARD ::QXMSMsg::SvrHealthReport* release_svrhealthreport();
  ::QXMSMsg::SvrHealthReport* mutable_svrhealthreport();
  void set_allocated_svrhealthreport(::QXMSMsg::SvrHealthReport* svrhealthreport);
  private:
  const ::QXMSMsg::SvrHealthReport& _internal_svrhealthreport() const;
  ::QXMSMsg::SvrHealthReport* _internal_mutable_svrhealthreport();
  public:
  void unsafe_arena_set_allocated_svrhealthreport(
      ::QXMSMsg::SvrHealthReport* svrhealthreport);
  ::QXMSMsg::SvrHealthReport* unsafe_arena_release_svrhealthreport();

  // uint32 msgType = 1;
  void clear_msgtype();
  uint32_t msgtype() const;
  void set_msgtype(uint32_t value);
  private:
  uint32_t _internal_msgtype() const;
  void _internal_set_msgtype(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:QXMSMsg.MsgBase)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::QXMSMsg::SvrHealthReport* svrhealthreport_;
    uint32_t msgtype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_QXMSMsg_2eproto;
};
// -------------------------------------------------------------------

class ClientInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QXMSMsg.ClientInfo) */ {
 public:
  inline ClientInfo() : ClientInfo(nullptr) {}
  ~ClientInfo() override;
  explicit PROTOBUF_CONSTEXPR ClientInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientInfo(const ClientInfo& from);
  ClientInfo(ClientInfo&& from) noexcept
    : ClientInfo() {
    *this = ::std::move(from);
  }

  inline ClientInfo& operator=(const ClientInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientInfo& operator=(ClientInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientInfo* internal_default_instance() {
    return reinterpret_cast<const ClientInfo*>(
               &_ClientInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ClientInfo& a, ClientInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ClientInfo& from) {
    ClientInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QXMSMsg.ClientInfo";
  }
  protected:
  explicit ClientInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 1,
  };
  // uint32 clientId = 1;
  void clear_clientid();
  uint32_t clientid() const;
  void set_clientid(uint32_t value);
  private:
  uint32_t _internal_clientid() const;
  void _internal_set_clientid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:QXMSMsg.ClientInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t clientid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_QXMSMsg_2eproto;
};
// -------------------------------------------------------------------

class SvrHealthReport final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QXMSMsg.SvrHealthReport) */ {
 public:
  inline SvrHealthReport() : SvrHealthReport(nullptr) {}
  ~SvrHealthReport() override;
  explicit PROTOBUF_CONSTEXPR SvrHealthReport(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SvrHealthReport(const SvrHealthReport& from);
  SvrHealthReport(SvrHealthReport&& from) noexcept
    : SvrHealthReport() {
    *this = ::std::move(from);
  }

  inline SvrHealthReport& operator=(const SvrHealthReport& from) {
    CopyFrom(from);
    return *this;
  }
  inline SvrHealthReport& operator=(SvrHealthReport&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SvrHealthReport& default_instance() {
    return *internal_default_instance();
  }
  static inline const SvrHealthReport* internal_default_instance() {
    return reinterpret_cast<const SvrHealthReport*>(
               &_SvrHealthReport_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SvrHealthReport& a, SvrHealthReport& b) {
    a.Swap(&b);
  }
  inline void Swap(SvrHealthReport* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SvrHealthReport* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SvrHealthReport* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SvrHealthReport>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SvrHealthReport& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SvrHealthReport& from) {
    SvrHealthReport::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SvrHealthReport* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QXMSMsg.SvrHealthReport";
  }
  protected:
  explicit SvrHealthReport(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientInfoFieldNumber = 3,
    kCpuUsageFieldNumber = 1,
    kMemUsageFieldNumber = 2,
  };
  // repeated .QXMSMsg.ClientInfo clientInfo = 3;
  int clientinfo_size() const;
  private:
  int _internal_clientinfo_size() const;
  public:
  void clear_clientinfo();
  ::QXMSMsg::ClientInfo* mutable_clientinfo(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::QXMSMsg::ClientInfo >*
      mutable_clientinfo();
  private:
  const ::QXMSMsg::ClientInfo& _internal_clientinfo(int index) const;
  ::QXMSMsg::ClientInfo* _internal_add_clientinfo();
  public:
  const ::QXMSMsg::ClientInfo& clientinfo(int index) const;
  ::QXMSMsg::ClientInfo* add_clientinfo();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::QXMSMsg::ClientInfo >&
      clientinfo() const;

  // float cpuUsage = 1;
  void clear_cpuusage();
  float cpuusage() const;
  void set_cpuusage(float value);
  private:
  float _internal_cpuusage() const;
  void _internal_set_cpuusage(float value);
  public:

  // float memUsage = 2;
  void clear_memusage();
  float memusage() const;
  void set_memusage(float value);
  private:
  float _internal_memusage() const;
  void _internal_set_memusage(float value);
  public:

  // @@protoc_insertion_point(class_scope:QXMSMsg.SvrHealthReport)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::QXMSMsg::ClientInfo > clientinfo_;
    float cpuusage_;
    float memusage_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_QXMSMsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MsgPayload

// uint32 transId = 1;
inline void MsgPayload::clear_transid() {
  _impl_.transid_ = 0u;
}
inline uint32_t MsgPayload::_internal_transid() const {
  return _impl_.transid_;
}
inline uint32_t MsgPayload::transid() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.MsgPayload.transId)
  return _internal_transid();
}
inline void MsgPayload::_internal_set_transid(uint32_t value) {
  
  _impl_.transid_ = value;
}
inline void MsgPayload::set_transid(uint32_t value) {
  _internal_set_transid(value);
  // @@protoc_insertion_point(field_set:QXMSMsg.MsgPayload.transId)
}

// uint64 timestamp = 2;
inline void MsgPayload::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t MsgPayload::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t MsgPayload::timestamp() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.MsgPayload.timestamp)
  return _internal_timestamp();
}
inline void MsgPayload::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void MsgPayload::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:QXMSMsg.MsgPayload.timestamp)
}

// string bussinessKey = 3;
inline void MsgPayload::clear_bussinesskey() {
  _impl_.bussinesskey_.ClearToEmpty();
}
inline const std::string& MsgPayload::bussinesskey() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.MsgPayload.bussinessKey)
  return _internal_bussinesskey();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MsgPayload::set_bussinesskey(ArgT0&& arg0, ArgT... args) {
 
 _impl_.bussinesskey_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:QXMSMsg.MsgPayload.bussinessKey)
}
inline std::string* MsgPayload::mutable_bussinesskey() {
  std::string* _s = _internal_mutable_bussinesskey();
  // @@protoc_insertion_point(field_mutable:QXMSMsg.MsgPayload.bussinessKey)
  return _s;
}
inline const std::string& MsgPayload::_internal_bussinesskey() const {
  return _impl_.bussinesskey_.Get();
}
inline void MsgPayload::_internal_set_bussinesskey(const std::string& value) {
  
  _impl_.bussinesskey_.Set(value, GetArenaForAllocation());
}
inline std::string* MsgPayload::_internal_mutable_bussinesskey() {
  
  return _impl_.bussinesskey_.Mutable(GetArenaForAllocation());
}
inline std::string* MsgPayload::release_bussinesskey() {
  // @@protoc_insertion_point(field_release:QXMSMsg.MsgPayload.bussinessKey)
  return _impl_.bussinesskey_.Release();
}
inline void MsgPayload::set_allocated_bussinesskey(std::string* bussinesskey) {
  if (bussinesskey != nullptr) {
    
  } else {
    
  }
  _impl_.bussinesskey_.SetAllocated(bussinesskey, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bussinesskey_.IsDefault()) {
    _impl_.bussinesskey_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:QXMSMsg.MsgPayload.bussinessKey)
}

// .QXMSMsg.ServerInfo serverInfo = 5;
inline bool MsgPayload::_internal_has_serverinfo() const {
  return this != internal_default_instance() && _impl_.serverinfo_ != nullptr;
}
inline bool MsgPayload::has_serverinfo() const {
  return _internal_has_serverinfo();
}
inline void MsgPayload::clear_serverinfo() {
  if (GetArenaForAllocation() == nullptr && _impl_.serverinfo_ != nullptr) {
    delete _impl_.serverinfo_;
  }
  _impl_.serverinfo_ = nullptr;
}
inline const ::QXMSMsg::ServerInfo& MsgPayload::_internal_serverinfo() const {
  const ::QXMSMsg::ServerInfo* p = _impl_.serverinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::QXMSMsg::ServerInfo&>(
      ::QXMSMsg::_ServerInfo_default_instance_);
}
inline const ::QXMSMsg::ServerInfo& MsgPayload::serverinfo() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.MsgPayload.serverInfo)
  return _internal_serverinfo();
}
inline void MsgPayload::unsafe_arena_set_allocated_serverinfo(
    ::QXMSMsg::ServerInfo* serverinfo) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.serverinfo_);
  }
  _impl_.serverinfo_ = serverinfo;
  if (serverinfo) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:QXMSMsg.MsgPayload.serverInfo)
}
inline ::QXMSMsg::ServerInfo* MsgPayload::release_serverinfo() {
  
  ::QXMSMsg::ServerInfo* temp = _impl_.serverinfo_;
  _impl_.serverinfo_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::QXMSMsg::ServerInfo* MsgPayload::unsafe_arena_release_serverinfo() {
  // @@protoc_insertion_point(field_release:QXMSMsg.MsgPayload.serverInfo)
  
  ::QXMSMsg::ServerInfo* temp = _impl_.serverinfo_;
  _impl_.serverinfo_ = nullptr;
  return temp;
}
inline ::QXMSMsg::ServerInfo* MsgPayload::_internal_mutable_serverinfo() {
  
  if (_impl_.serverinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::QXMSMsg::ServerInfo>(GetArenaForAllocation());
    _impl_.serverinfo_ = p;
  }
  return _impl_.serverinfo_;
}
inline ::QXMSMsg::ServerInfo* MsgPayload::mutable_serverinfo() {
  ::QXMSMsg::ServerInfo* _msg = _internal_mutable_serverinfo();
  // @@protoc_insertion_point(field_mutable:QXMSMsg.MsgPayload.serverInfo)
  return _msg;
}
inline void MsgPayload::set_allocated_serverinfo(::QXMSMsg::ServerInfo* serverinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.serverinfo_;
  }
  if (serverinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(serverinfo);
    if (message_arena != submessage_arena) {
      serverinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, serverinfo, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.serverinfo_ = serverinfo;
  // @@protoc_insertion_point(field_set_allocated:QXMSMsg.MsgPayload.serverInfo)
}

// int32 errCode = 6;
inline void MsgPayload::clear_errcode() {
  _impl_.errcode_ = 0;
}
inline int32_t MsgPayload::_internal_errcode() const {
  return _impl_.errcode_;
}
inline int32_t MsgPayload::errcode() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.MsgPayload.errCode)
  return _internal_errcode();
}
inline void MsgPayload::_internal_set_errcode(int32_t value) {
  
  _impl_.errcode_ = value;
}
inline void MsgPayload::set_errcode(int32_t value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:QXMSMsg.MsgPayload.errCode)
}

// .QXMSMsg.MsgBase msgBase = 7;
inline bool MsgPayload::_internal_has_msgbase() const {
  return this != internal_default_instance() && _impl_.msgbase_ != nullptr;
}
inline bool MsgPayload::has_msgbase() const {
  return _internal_has_msgbase();
}
inline void MsgPayload::clear_msgbase() {
  if (GetArenaForAllocation() == nullptr && _impl_.msgbase_ != nullptr) {
    delete _impl_.msgbase_;
  }
  _impl_.msgbase_ = nullptr;
}
inline const ::QXMSMsg::MsgBase& MsgPayload::_internal_msgbase() const {
  const ::QXMSMsg::MsgBase* p = _impl_.msgbase_;
  return p != nullptr ? *p : reinterpret_cast<const ::QXMSMsg::MsgBase&>(
      ::QXMSMsg::_MsgBase_default_instance_);
}
inline const ::QXMSMsg::MsgBase& MsgPayload::msgbase() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.MsgPayload.msgBase)
  return _internal_msgbase();
}
inline void MsgPayload::unsafe_arena_set_allocated_msgbase(
    ::QXMSMsg::MsgBase* msgbase) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.msgbase_);
  }
  _impl_.msgbase_ = msgbase;
  if (msgbase) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:QXMSMsg.MsgPayload.msgBase)
}
inline ::QXMSMsg::MsgBase* MsgPayload::release_msgbase() {
  
  ::QXMSMsg::MsgBase* temp = _impl_.msgbase_;
  _impl_.msgbase_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::QXMSMsg::MsgBase* MsgPayload::unsafe_arena_release_msgbase() {
  // @@protoc_insertion_point(field_release:QXMSMsg.MsgPayload.msgBase)
  
  ::QXMSMsg::MsgBase* temp = _impl_.msgbase_;
  _impl_.msgbase_ = nullptr;
  return temp;
}
inline ::QXMSMsg::MsgBase* MsgPayload::_internal_mutable_msgbase() {
  
  if (_impl_.msgbase_ == nullptr) {
    auto* p = CreateMaybeMessage<::QXMSMsg::MsgBase>(GetArenaForAllocation());
    _impl_.msgbase_ = p;
  }
  return _impl_.msgbase_;
}
inline ::QXMSMsg::MsgBase* MsgPayload::mutable_msgbase() {
  ::QXMSMsg::MsgBase* _msg = _internal_mutable_msgbase();
  // @@protoc_insertion_point(field_mutable:QXMSMsg.MsgPayload.msgBase)
  return _msg;
}
inline void MsgPayload::set_allocated_msgbase(::QXMSMsg::MsgBase* msgbase) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.msgbase_;
  }
  if (msgbase) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(msgbase);
    if (message_arena != submessage_arena) {
      msgbase = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msgbase, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.msgbase_ = msgbase;
  // @@protoc_insertion_point(field_set_allocated:QXMSMsg.MsgPayload.msgBase)
}

// -------------------------------------------------------------------

// ServerInfo

// uint32 serverId = 1;
inline void ServerInfo::clear_serverid() {
  _impl_.serverid_ = 0u;
}
inline uint32_t ServerInfo::_internal_serverid() const {
  return _impl_.serverid_;
}
inline uint32_t ServerInfo::serverid() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.ServerInfo.serverId)
  return _internal_serverid();
}
inline void ServerInfo::_internal_set_serverid(uint32_t value) {
  
  _impl_.serverid_ = value;
}
inline void ServerInfo::set_serverid(uint32_t value) {
  _internal_set_serverid(value);
  // @@protoc_insertion_point(field_set:QXMSMsg.ServerInfo.serverId)
}

// string serverName = 2;
inline void ServerInfo::clear_servername() {
  _impl_.servername_.ClearToEmpty();
}
inline const std::string& ServerInfo::servername() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.ServerInfo.serverName)
  return _internal_servername();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerInfo::set_servername(ArgT0&& arg0, ArgT... args) {
 
 _impl_.servername_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:QXMSMsg.ServerInfo.serverName)
}
inline std::string* ServerInfo::mutable_servername() {
  std::string* _s = _internal_mutable_servername();
  // @@protoc_insertion_point(field_mutable:QXMSMsg.ServerInfo.serverName)
  return _s;
}
inline const std::string& ServerInfo::_internal_servername() const {
  return _impl_.servername_.Get();
}
inline void ServerInfo::_internal_set_servername(const std::string& value) {
  
  _impl_.servername_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerInfo::_internal_mutable_servername() {
  
  return _impl_.servername_.Mutable(GetArenaForAllocation());
}
inline std::string* ServerInfo::release_servername() {
  // @@protoc_insertion_point(field_release:QXMSMsg.ServerInfo.serverName)
  return _impl_.servername_.Release();
}
inline void ServerInfo::set_allocated_servername(std::string* servername) {
  if (servername != nullptr) {
    
  } else {
    
  }
  _impl_.servername_.SetAllocated(servername, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.servername_.IsDefault()) {
    _impl_.servername_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:QXMSMsg.ServerInfo.serverName)
}

// -------------------------------------------------------------------

// MsgBase

// uint32 msgType = 1;
inline void MsgBase::clear_msgtype() {
  _impl_.msgtype_ = 0u;
}
inline uint32_t MsgBase::_internal_msgtype() const {
  return _impl_.msgtype_;
}
inline uint32_t MsgBase::msgtype() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.MsgBase.msgType)
  return _internal_msgtype();
}
inline void MsgBase::_internal_set_msgtype(uint32_t value) {
  
  _impl_.msgtype_ = value;
}
inline void MsgBase::set_msgtype(uint32_t value) {
  _internal_set_msgtype(value);
  // @@protoc_insertion_point(field_set:QXMSMsg.MsgBase.msgType)
}

// .QXMSMsg.SvrHealthReport svrHealthReport = 2;
inline bool MsgBase::_internal_has_svrhealthreport() const {
  return this != internal_default_instance() && _impl_.svrhealthreport_ != nullptr;
}
inline bool MsgBase::has_svrhealthreport() const {
  return _internal_has_svrhealthreport();
}
inline void MsgBase::clear_svrhealthreport() {
  if (GetArenaForAllocation() == nullptr && _impl_.svrhealthreport_ != nullptr) {
    delete _impl_.svrhealthreport_;
  }
  _impl_.svrhealthreport_ = nullptr;
}
inline const ::QXMSMsg::SvrHealthReport& MsgBase::_internal_svrhealthreport() const {
  const ::QXMSMsg::SvrHealthReport* p = _impl_.svrhealthreport_;
  return p != nullptr ? *p : reinterpret_cast<const ::QXMSMsg::SvrHealthReport&>(
      ::QXMSMsg::_SvrHealthReport_default_instance_);
}
inline const ::QXMSMsg::SvrHealthReport& MsgBase::svrhealthreport() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.MsgBase.svrHealthReport)
  return _internal_svrhealthreport();
}
inline void MsgBase::unsafe_arena_set_allocated_svrhealthreport(
    ::QXMSMsg::SvrHealthReport* svrhealthreport) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.svrhealthreport_);
  }
  _impl_.svrhealthreport_ = svrhealthreport;
  if (svrhealthreport) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:QXMSMsg.MsgBase.svrHealthReport)
}
inline ::QXMSMsg::SvrHealthReport* MsgBase::release_svrhealthreport() {
  
  ::QXMSMsg::SvrHealthReport* temp = _impl_.svrhealthreport_;
  _impl_.svrhealthreport_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::QXMSMsg::SvrHealthReport* MsgBase::unsafe_arena_release_svrhealthreport() {
  // @@protoc_insertion_point(field_release:QXMSMsg.MsgBase.svrHealthReport)
  
  ::QXMSMsg::SvrHealthReport* temp = _impl_.svrhealthreport_;
  _impl_.svrhealthreport_ = nullptr;
  return temp;
}
inline ::QXMSMsg::SvrHealthReport* MsgBase::_internal_mutable_svrhealthreport() {
  
  if (_impl_.svrhealthreport_ == nullptr) {
    auto* p = CreateMaybeMessage<::QXMSMsg::SvrHealthReport>(GetArenaForAllocation());
    _impl_.svrhealthreport_ = p;
  }
  return _impl_.svrhealthreport_;
}
inline ::QXMSMsg::SvrHealthReport* MsgBase::mutable_svrhealthreport() {
  ::QXMSMsg::SvrHealthReport* _msg = _internal_mutable_svrhealthreport();
  // @@protoc_insertion_point(field_mutable:QXMSMsg.MsgBase.svrHealthReport)
  return _msg;
}
inline void MsgBase::set_allocated_svrhealthreport(::QXMSMsg::SvrHealthReport* svrhealthreport) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.svrhealthreport_;
  }
  if (svrhealthreport) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(svrhealthreport);
    if (message_arena != submessage_arena) {
      svrhealthreport = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, svrhealthreport, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.svrhealthreport_ = svrhealthreport;
  // @@protoc_insertion_point(field_set_allocated:QXMSMsg.MsgBase.svrHealthReport)
}

// -------------------------------------------------------------------

// ClientInfo

// uint32 clientId = 1;
inline void ClientInfo::clear_clientid() {
  _impl_.clientid_ = 0u;
}
inline uint32_t ClientInfo::_internal_clientid() const {
  return _impl_.clientid_;
}
inline uint32_t ClientInfo::clientid() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.ClientInfo.clientId)
  return _internal_clientid();
}
inline void ClientInfo::_internal_set_clientid(uint32_t value) {
  
  _impl_.clientid_ = value;
}
inline void ClientInfo::set_clientid(uint32_t value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:QXMSMsg.ClientInfo.clientId)
}

// -------------------------------------------------------------------

// SvrHealthReport

// float cpuUsage = 1;
inline void SvrHealthReport::clear_cpuusage() {
  _impl_.cpuusage_ = 0;
}
inline float SvrHealthReport::_internal_cpuusage() const {
  return _impl_.cpuusage_;
}
inline float SvrHealthReport::cpuusage() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.SvrHealthReport.cpuUsage)
  return _internal_cpuusage();
}
inline void SvrHealthReport::_internal_set_cpuusage(float value) {
  
  _impl_.cpuusage_ = value;
}
inline void SvrHealthReport::set_cpuusage(float value) {
  _internal_set_cpuusage(value);
  // @@protoc_insertion_point(field_set:QXMSMsg.SvrHealthReport.cpuUsage)
}

// float memUsage = 2;
inline void SvrHealthReport::clear_memusage() {
  _impl_.memusage_ = 0;
}
inline float SvrHealthReport::_internal_memusage() const {
  return _impl_.memusage_;
}
inline float SvrHealthReport::memusage() const {
  // @@protoc_insertion_point(field_get:QXMSMsg.SvrHealthReport.memUsage)
  return _internal_memusage();
}
inline void SvrHealthReport::_internal_set_memusage(float value) {
  
  _impl_.memusage_ = value;
}
inline void SvrHealthReport::set_memusage(float value) {
  _internal_set_memusage(value);
  // @@protoc_insertion_point(field_set:QXMSMsg.SvrHealthReport.memUsage)
}

// repeated .QXMSMsg.ClientInfo clientInfo = 3;
inline int SvrHealthReport::_internal_clientinfo_size() const {
  return _impl_.clientinfo_.size();
}
inline int SvrHealthReport::clientinfo_size() const {
  return _internal_clientinfo_size();
}
inline void SvrHealthReport::clear_clientinfo() {
  _impl_.clientinfo_.Clear();
}
inline ::QXMSMsg::ClientInfo* SvrHealthReport::mutable_clientinfo(int index) {
  // @@protoc_insertion_point(field_mutable:QXMSMsg.SvrHealthReport.clientInfo)
  return _impl_.clientinfo_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::QXMSMsg::ClientInfo >*
SvrHealthReport::mutable_clientinfo() {
  // @@protoc_insertion_point(field_mutable_list:QXMSMsg.SvrHealthReport.clientInfo)
  return &_impl_.clientinfo_;
}
inline const ::QXMSMsg::ClientInfo& SvrHealthReport::_internal_clientinfo(int index) const {
  return _impl_.clientinfo_.Get(index);
}
inline const ::QXMSMsg::ClientInfo& SvrHealthReport::clientinfo(int index) const {
  // @@protoc_insertion_point(field_get:QXMSMsg.SvrHealthReport.clientInfo)
  return _internal_clientinfo(index);
}
inline ::QXMSMsg::ClientInfo* SvrHealthReport::_internal_add_clientinfo() {
  return _impl_.clientinfo_.Add();
}
inline ::QXMSMsg::ClientInfo* SvrHealthReport::add_clientinfo() {
  ::QXMSMsg::ClientInfo* _add = _internal_add_clientinfo();
  // @@protoc_insertion_point(field_add:QXMSMsg.SvrHealthReport.clientInfo)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::QXMSMsg::ClientInfo >&
SvrHealthReport::clientinfo() const {
  // @@protoc_insertion_point(field_list:QXMSMsg.SvrHealthReport.clientInfo)
  return _impl_.clientinfo_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace QXMSMsg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::QXMSMsg::MsgType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::QXMSMsg::MsgType>() {
  return ::QXMSMsg::MsgType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_QXMSMsg_2eproto
